# Generated by Django 3.0.4 on 2020-03-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('birthday', models.DateTimeField(default='SOME INTEGER')),
                ('flag', models.CharField(choices=[('visa', 'Visa'), ('itau', 'Itaú'), ('caixa', 'Caixa'), ('santander', 'Santander'), ('bbrasil', 'BancoDoBrasil'), ('bradesco', 'bradesco'), ('inter', 'BancoInter'), ('nubank', 'Nubank')], max_length=10)),
                ('cardNumber', models.CharField(max_length=16)),
                ('cardName', models.CharField(max_length=255)),
                ('medicdescription', models.TextField()),
                ('typePlan', models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('a', 'Anual')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
