# Generated by Django 3.0.4 on 2020-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200323_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergym',
            name='birthday',
            field=models.DateTimeField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='usergym',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
